# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Unknown', max_length=30)),
                ('tournament_type', models.CharField(default=b'leage', max_length=10)),
                ('loops_quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default=b'new', max_length=10)),
            ],
        ),
    ]
