# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20170401_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='round',
            new_name='tour',
        ),
    ]
